$(document).ready(function(){
    $('.burger_menu').click(function(){
        $('.topnav').show();
        $('.burger_menu').hide();
    });
     $('.burger_close').click(function(){
         $('.topnav').hide();
          $('.burger_menu').show();
     });
});